version: '2'

services:

  pavlichenko-bot:
    image: pavlichenko-bot
    restart: always
    build:
      context: ../app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ../data:/data
